
#Before run rename file to docker-compose.yml
version: '2'

networks:
  service-tier:
    external: true
  app:

volumes:
  uploads:
  dbdata:
  esdata:
  static:
  redisdata:
  export:

services:
  nginx:
    restart: always
    image: nginx:stable
    container_name: "${PROJECT_NAME}_nginx"
    networks:
      - app
      - service-tier
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - static:/static
      - uploads:/static/uploads
      - export:/export
    labels:
      - "traefik.backend=${PROJECT_NAME}_nginx"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.docker.network=service-tier"
      - "traefik.port=80"
      - "traefik.enable=true"
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_NETWORK: app      
  app:
    restart: always
    container_name: "${PROJECT_NAME}_app"
    image: "${REGISTRY}/${PROJECT_NAME}:latest"
    volumes:
      - uploads:/app/public/uploads
      - static:/app/static
    networks:
      - app
    environment:     
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}      
      RAILS_LOG_TO_STDOUT: "true"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ELASTICSEARCH_URL: http://elasticsearch:9200
      JOB_WORKER_URL: ${JOB_WORKER_URL}
      REDIS_URL: ${REDIS_URL}
  elasticsearch:
    restart: always
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    networks:
      - app
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  redis:
    image: redis:latest
    networks:
      - app
    volumes:
      - redisdata:/data
  sidekiq:
    image: "${REGISTRY}/${PROJECT_NAME}:latest"
    volumes:
      - static:/app/public/uploads
      - export:/app/public/export
    entrypoint: ./bin/sidekiq.sh
    networks:
      - app
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_LOG_TO_STDOUT: "true"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

