logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "your@email"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = true
acmeLogging = true


[acme.httpChallenge]
  entryPoint = "http"

[docker]
watch = true
exposedbydefault = false
endpoint = "unix:///var/run/docker.sock"

